### PR TITLE
feat: ide setup for golang with lsp, formatting and debugging

### PR DESCRIPTION
**Pull request by ritchielrez**
Hi!
I am trying to solve this issue https://github.com/LunarVim/starter.lvim/issues/3
I have made sure that Golang formatting, linting, LSP and debugging support has properly been added.

As for the formatter, goimports support through [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) has been added. This config also ensures that
go treesitter parser gets installed automatically. gopls support for LSP and delve support for debugging
also had been added through [dap-go](https://github.com/leoluz/nvim-dap-go) and [dap-ui](https://github.com/rcarriga/nvim-dap-ui).

Please have a look and provide feedback if needed.

### CODE REVIEW

**Comment by longwuyuan** [comment]
Love this. Hope it merges soon. Thank you very much

**Comment by ritchielrez** [comment]
> Love this. Hope it merges soon. Thank you very much

Thanks for the feedback!

**Comment by ChristianChiarulli** [comment]
sorry I caught this too late

**Comment by ritchielrez** [comment]
> sorry I caught this too late

Thanks for the merge!

**Comment by longwuyuan** [comment]
@ritchielrez , i thought I understood this well but I am unable to solve my problem.
- I configured my lunarvim after seeting the changes you had proposed
- I assumed I understood how to use dap
- That means I created those ftplugin and other directories and manually created those files with the contenst I saw in the PR
- now I have updated and I don't know how to set breakpoint
- i see i have to type :debug to start debug
- This whole experience is perfect in Fatih's vim-go but i am stuck here

Any chance you can give me tips on how to become able to run debug and how to add breakpoints

**Comment by longwuyuan** [comment]
Ah, just discoverd shortcut space+d is debug menu. Thank you very very much. Regards

**Pull request closed without merging**
