### PR TITLE
minimal ide setup for c/c++

### LINKED ISSUE #5: [Hacktoberfest] C/C++ IDE
- formatters
- linters
- debugging
- branch name c-ide

### PR DESCRIPTION
**Pull request by 0x736d**
Tris to fix #5
- setup lsp(`clangd`) with some small manual configurations
- configure debugger adapter(`codelldb`)

There is no need to setup additional formatters and linters since `clangd` embeds `clang-tidy` and `clang-format`

### CODE REVIEW

**Review by ChristianChiarulli — APPROVED** [review]

**Comment by abzcoding** [comment]
@0x736d can we have this in it as well ( a lot of people face this issue [3050](https://github.com/LunarVim/LunarVim/issues/3050), [2597](https://github.com/LunarVim/LunarVim/issues/2597))

```
+  local capabilities = require("lvim.lsp").common_capabilities()
+  capabilities.offsetEncoding = { "utf-16" }


-      capabilities = require("lvim.lsp").common_capabilities(),
+      capabilities = capabilities,
```

**Comment by 0x736d** [comment]
@abzcoding added in #14.

Also we need to pass `--offset-encoding=utf-16` to `clangd` as well.. right ?

**Comment by abzcoding** [comment]
> @abzcoding added in #14.
> 
> Also we need to pass `--offset-encoding=utf-16` to `clangd` as well.. right ?

Thanks, only adding the capability would suffice. (at least I think so)

**Comment by 0x736d** [comment]
> > @abzcoding added in #14.
> > Also we need to pass `--offset-encoding=utf-16` to `clangd` as well.. right ?
> 
> Thanks, only adding the capability would suffice. (at least I think so)

I tested both cases and got no errors so far.

**Pull request merged**
